[package]
name = "data_prep"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
backend = { path = "../../backend" }
bincode.workspace = true
csv = "1.3.0"
geo.workspace = true
geojson.workspace = true
serde.workspace = true
utils.workspace = true
